"""add_category_to_challenge_templates

Revision ID: 29a6d07026d2
Revises: 66b462177601
Create Date: 2025-09-02 09:24:53.921128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a6d07026d2'
down_revision = '66b462177601'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_templates', sa.Column('category', sa.Enum('STOCKS', 'CRYPTO', name='challengecategory'), nullable=False))
    op.add_column('trades', sa.Column('trading_challenge_id', sa.UUID(), nullable=True))
    op.add_column('trades', sa.Column('instrument_id', sa.UUID(), nullable=False))
    op.drop_index('ix_trades_instrument', table_name='trades')
    op.create_index(op.f('ix_trades_instrument_id'), 'trades', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_trades_trading_challenge_id'), 'trades', ['trading_challenge_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'trades', 'trading_challenges', ['trading_challenge_id'], ['challenge_id'])
    op.drop_column('trades', 'instrument')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('instrument', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_trading_challenge_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument_id'), table_name='trades')
    op.create_index('ix_trades_instrument', 'trades', ['instrument'], unique=False)
    op.drop_column('trades', 'instrument_id')
    op.drop_column('trades', 'trading_challenge_id')
    op.drop_column('challenge_templates', 'category')
    # ### end Alembic commands ###
