"""add_category_to_challenge_selections

Revision ID: 5f345e9c1ca7
Revises: 29a6d07026d2
Create Date: 2025-09-02 10:37:11.323860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f345e9c1ca7'
down_revision = '29a6d07026d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('challenge_selections', sa.Column('category', sa.Enum('STOCKS', 'CRYPTO', name='challengecategory'), nullable=True))
    
    # Update existing records to have STOCKS as default category
    op.execute("UPDATE challenge_selections SET category = 'STOCKS' WHERE category IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('challenge_selections', 'category', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_selections', 'category')
    # ### end Alembic commands ###
