"""Add challenge_selections and trading_challenges tables

Revision ID: 66b462177601
Revises: fa8ba1f524fb
Create Date: 2025-08-31 17:07:18.271865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b462177601'
down_revision = 'fa8ba1f524fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
