"""Add hashed_password field to users table

Revision ID: c7493c2ff0b0
Revises: 3a5632d2e11b
Create Date: 2025-08-31 14:12:53.634637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7493c2ff0b0'
down_revision = '3a5632d2e11b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_templates', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('challenge_templates', sa.Column('challenge_type', sa.Enum('FUNDED', 'DEMO', 'EVALUATION', name='challengetype'), nullable=False))
    op.add_column('challenge_templates', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('challenge_templates', sa.Column('min_trading_days', sa.Numeric(precision=3, scale=0), nullable=True))
    op.add_column('challenge_templates', sa.Column('max_challenge_days', sa.Numeric(precision=4, scale=0), nullable=True))
    op.add_column('challenge_templates', sa.Column('weekend_holding', sa.Boolean(), nullable=False))
    op.add_column('challenge_templates', sa.Column('news_trading', sa.Boolean(), nullable=False))
    op.add_column('challenge_templates', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('challenge_templates', sa.Column('sort_order', sa.Numeric(precision=3, scale=0), nullable=True))
    op.add_column('challenge_templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('challenge_templates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('challenge_templates', 'updated_at')
    op.drop_column('challenge_templates', 'created_at')
    op.drop_column('challenge_templates', 'sort_order')
    op.drop_column('challenge_templates', 'is_featured')
    op.drop_column('challenge_templates', 'news_trading')
    op.drop_column('challenge_templates', 'weekend_holding')
    op.drop_column('challenge_templates', 'max_challenge_days')
    op.drop_column('challenge_templates', 'min_trading_days')
    op.drop_column('challenge_templates', 'currency')
    op.drop_column('challenge_templates', 'challenge_type')
    op.drop_column('challenge_templates', 'description')
    # ### end Alembic commands ###
