"""Add challenge_selections table

Revision ID: fa8ba1f524fb
Revises: c7493c2ff0b0
Create Date: 2025-08-31 16:52:36.851892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa8ba1f524fb'
down_revision = 'c7493c2ff0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_selections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_selections',
    sa.Column('selection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('profit_target', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('max_drawdown', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('daily_limit', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='challengeselectionstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='challenge_selections_user_id_fkey'),
    sa.PrimaryKeyConstraint('selection_id', name='challenge_selections_pkey')
    )
    # ### end Alembic commands ###
